# Copyright 2021 Ichigo Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Set environment variables to be used in the build process
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
      - go mod tidy
builds:
  - env:
        - CGO_ENABLED=0
    binary: addlicense
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - 386

archives:
  - format: tar.gz
    format_overrides:
        - goos: windows
          format: zip
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
    replacements:
        amd64: 64bit
        386: 32bit
        arm: ARM
        arm64: ARM64
        darwin: macOS
        linux: Linux
        windows: Windows
    files:
        - README.md

snapshot:
  name_template: '{{ .Tag }}-next'