# Copyright (c) 2021 Ichigo Project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Set environment variables to be used in the build process
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
      - go mod tidy
builds:
  - env:
        - CGO_ENABLED=0
    binary: addlicense
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - 386

archives:
  - format: tar.gz
    format_overrides:
        - goos: windows
          format: zip
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
    replacements:
        amd64: 64bit
        386: 32bit
        arm: ARM
        arm64: ARM64
        darwin: macOS
        linux: Linux
        windows: Windows
    files:
        - README.md

snapshot:
  name_template: '{{ .Tag }}-next'